# Generated by Django 4.2.9 on 2024-01-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuddyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("Address", models.TextField()),
                ("Phone_Number", models.IntegerField()),
                (
                    "Addres_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BuddyInfo",
                        to="book.addressbook",
                    ),
                ),
            ],
        ),
    ]
