# Generated by Django 4.2.9 on 2024-01-20 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_buddyinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buddyinfo",
            old_name="Addres_book",
            new_name="Address_book",
        ),
    ]
